### ISSUE TITLE
Seemingly random crashes when fuzzy matching

### ISSUE THREAD

**Issue by imatpot** [Saghen/blink.cmp#2031]
### Make sure you have done the following

- [x] Updated to the latest version of `blink.cmp`
- [x] Searched for existing issues and documentation (try `<C-k>` on https://cmp.saghen.dev)

### Bug Description

blink.cmp randomly spits out an error when loading completions, trying to index an empty list during fuzzy matching. i can't quite figure out how to reproduce it, but i did manage to get the affected file from the error that appeared, indicating that it's the fuzzy matching:

```
thread '<unnamed>' panicked at /private/tmp/nix-build-blink-fuzzy-lib-1.6.0.drv-0/blink-fuzzy-lib-1.6.0-vendor/frizbee-0.5.0/src/smith_waterman/reference/indices.rs:23:21: index out of bounds: the len is 0 but the index is 0
```

there is a [related issue in frizbee](https://github.com/Saghen/frizbee/issues/38) but the author was advised to report here, although i couldn't find an issue referincing back to it in this repo. like said author, i also couldn't find the exact culprit of this error — it "just happens". it also doesn't seem to be caused by any specific source

### Relevant configuration

```lua

```

### `neovim` version

0.11.3

### `blink.cmp` version

1.6.0

**Comment by BenjaminPalko** [comment]
I started experiencing crashes when using qmlls, dug through my journalctl which led me here. Whole IDE crashes out seemingly at random, before I get the crash out I get some weird issues like files not saving (reverts back to disk-state on save)

Here is the log Im seeing when nvim crashes

EDIT: I'm using Lazyvims default config for blink
```text
2025-07-26T21:52:25-04:00 baobeld-desktop systemd-coredump[767142]: Process 758701 (nvim) of user 1000 dumped core.
                                                                    
                                                                    Module libblink_cmp_fuzzy.so without build-id.
                                                                    Stack trace of thread 758701:
                                                                    #0  0x00007fb89059474c n/a (libc.so.6 + 0x9774c)
                                                                    #1  0x00007fb89053adc0 raise (libc.so.6 + 0x3ddc0)
                                                                    #2  0x00007fb89052257a abort (libc.so.6 + 0x2557a)
                                                                    #3  0x00007fb8905224e3 n/a (libc.so.6 + 0x254e3)
                                                                    #4  0x000055a5f718613f n/a (/usr/bin/nvim + 0x4d13f)
                                                                    #5  0x000055a5f72cfb23 extmark_splice_impl (/usr/bin/nvim + 0x196b23)
                                                                    #6  0x000055a5f7198443 nvim_buf_set_lines (/usr/bin/nvim + 0x5f443)
                                                                    #7  0x000055a5f731b819 n/a (/usr/bin/nvim + 0x1e2819)
                                                                    #8  0x00007fb890851f06 n/a (libluajit-5.1.so.2 + 0x6f06)
                                                                    #9  0x00007fb890868ad0 lua_pcall (libluajit-5.1.so.2 + 0x1dad0)
                                                                    #10 0x000055a5f7341be4 nlua_pcall (/usr/bin/nvim + 0x208be4)
                                                                    #11 0x000055a5f7345200 nlua_call_ref_ctx (/usr/bin/nvim + 0x20c200)
                                                                    #12 0x000055a5f71dba3f getnextac (/usr/bin/nvim + 0xa2a3f)
                                                                    #13 0x000055a5f72a92ee do_cmdline (/usr/bin/nvim + 0x1702ee)
                                                                    #14 0x000055a5f71d9944 apply_autocmds_group (/usr/bin/nvim + 0xa0944)
                                                                    #15 0x000055a5f71e918c n/a (/usr/bin/nvim + 0xb018c)
                                                                    #16 0x000055a5f71eb22d buf_write (/usr/bin/nvim + 0xb222d)
                                                                    #17 0x000055a5f729b630 do_write (/usr/bin/nvim + 0x162630)
                                                                    #18 0x000055a5f72a5a75 n/a (/usr/bin/nvim + 0x16ca75)
                                                                    #19 0x000055a5f72a9436 do_cmdline (/usr/bin/nvim + 0x170436)
                                                                    #20 0x000055a5f73a0cee n/a (/usr/bin/nvim + 0x267cee)
                                                                    #21 0x000055a5f739e46f n/a (/usr/bin/nvim + 0x26546f)
                                                                    #22 0x000055a5f74758a4 state_enter (/usr/bin/nvim + 0x33c8a4)
                                                                    #23 0x000055a5f739be96 normal_enter (/usr/bin/nvim + 0x262e96)
                                                                    #24 0x000055a5f718f2c0 main (/usr/bin/nvim + 0x562c0)
                                                                    #25 0x00007fb8905246b5 n/a (libc.so.6 + 0x276b5)
                                                                    #26 0x00007fb890524769 __libc_start_main (libc.so.6 + 0x27769)
                                                                    #27 0x000055a5f7191025 _start (/usr/bin/nvim + 0x58025)
                                                                    
                                                                    Stack trace of thread 759649:
                                                                    #0  0x00007fb89059ae22 n/a (libc.so.6 + 0x9de22)
                                                                    #1  0x00007fb89058efda n/a (libc.so.6 + 0x91fda)
                                                                    #2  0x00007fb89058f64c n/a (libc.so.6 + 0x9264c)
                                                                    #3  0x00007fb890591d1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                                    #4  0x00007fb89073a34e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                                    #5  0x00007fb89072f427 n/a (libuv.so.1 + 0x15427)
                                                                    #6  0x00007fb8905927eb n/a (libc.so.6 + 0x957eb)
                                                                    #7  0x00007fb89061620c n/a (libc.so.6 + 0x11920c)
                                                                    
                                                                    Stack trace of thread 759648:
                                                                    #0  0x00007fb89059ae22 n/a (libc.so.6 + 0x9de22)
                                                                    #1  0x00007fb89058efda n/a (libc.so.6 + 0x91fda)
                                                                    #2  0x00007fb89058f64c n/a (libc.so.6 + 0x9264c)
                                                                    #3  0x00007fb890591d1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                                    #4  0x00007fb89073a34e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                                    #5  0x00007fb89072f427 n/a (libuv.so.1 + 0x15427)
                                                                    #6  0x00007fb8905927eb n/a (libc.so.6 + 0x957eb)
                                                                    #7  0x00007fb89061620c n/a (libc.so.6 + 0x11920c)
                                                                    
                                                                    Stack trace of thread 759647:
                                                                    #0  0x00007fb89059ae22 n/a (libc.so.6 + 0x9de22)
                                                                    #1  0x00007fb89058efda n/a (libc.so.6 + 0x91fda)
                                                                    #2  0x00007fb89058f64c n/a (libc.so.6 + 0x9264c)
                                                                    #3  0x00007fb890591d1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                                    #4  0x00007fb89073a34e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                                    #5  0x00007fb89072f427 n/a (libuv.so.1 + 0x15427)
                                                                    #6  0x00007fb8905927eb n/a (libc.so.6 + 0x957eb)
                                                                    #7  0x00007fb89061620c n/a (libc.so.6 + 0x11920c)
                                                                    
                                                                    Stack trace of thread 759650:
                                                                    #0  0x00007fb89059ae22 n/a (libc.so.6 + 0x9de22)
                                                                    #1  0x00007fb89058efda n/a (libc.so.6 + 0x91fda)
                                                                    #2  0x00007fb89058f64c n/a (libc.so.6 + 0x9264c)
                                                                    #3  0x00007fb890591d1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                                    #4  0x00007fb89073a34e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                                    #5  0x00007fb89072f427 n/a (libuv.so.1 + 0x15427)
                                                                    #6  0x00007fb8905927eb n/a (libc.so.6 + 0x957eb)
                                                                    #7  0x00007fb89061620c n/a (libc.so.6 + 0x11920c)
                                                                    ELF object binary architecture: AMD x86-64
2025-07-26T21:52:25-04:00 baobeld-desktop systemd[1]: systemd-coredump@55-767141-0.service: Deactivated successfully.
2025-07-26T21:52:25-04:00 baobeld-desktop systemd[1]: systemd-coredump@55-767141-0.service: Consumed 428ms CPU time, 112.8M memory peak.
```

**Comment by logkn** [comment]
Experiencing the same issue:

### Context

My blink.cmp config:
```lua
return {
  'saghen/blink.cmp',
  -- optional: provides snippets for the snippet source
  dependencies = { 'rafamadriz/friendly-snippets', 'supermaven-inc/supermaven-nvim', 'huijiro/blink-cmp-supermaven' },

  -- use a release tag to download pre-built binaries
  version = '1.*',
  -- AND/OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
  -- build = 'cargo build --release',
  -- If you use nix, you can build from source using latest nightly rust with:
  -- build = 'nix run .#build-plugin',

  ---@module 'blink.cmp'

  ---@type blink.cmp.Config
  opts = {
    -- 'default' (recommended) for mappings similar to built-in completions (C-y to accept)
    -- 'super-tab' for mappings similar to vscode (tab to accept)
    -- 'enter' for enter to accept
    -- 'none' for no mappings
    --
    -- All presets have the following mappings:
    -- C-space: Open menu or open docs if already open
    -- C-n/C-p or Up/Down: Select next/previous item
    -- C-e: Hide menu
    -- C-k: Toggle signature help (if signature.enabled = true)
    --
    -- See :h blink-cmp-config-keymap for defining your own keymap
    keymap = { preset = 'default', ['<C-c>'] = {
      function(cmp)
        cmp.show { providers = { 'supermaven' } }
      end,
    } },

    appearance = {
      -- 'mono' (default) for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
      -- Adjusts spacing to ensure icons are aligned
      use_nvim_cmp_as_default = false,
      nerd_font_variant = 'mono',
    },

    completion = {
      documentation = { auto_show = true, auto_show_delay_ms = 200 },
      accept = { auto_brackets = { enabled = true } },
      ghost_text = { enabled = true },
    },

    -- Default list of enabled providers defined so that you can extend it
    -- elsewhere in your config, without redefining it, due to `opts_extend`
    sources = {
      -- default = { 'lsp', 'path', 'snippets', 'buffer', 'supermaven' },
      default = { 'lsp', 'path', 'snippets', 'buffer' },
      compat = {},
      providers = {
        supermaven = {
          name = 'supermaven',
          module = 'blink-cmp-supermaven',
          async = true,
        },
      },
    },

    -- (Default) Rust fuzzy matcher for typo resistance and significantly better performance
    -- You may use a lua implementation instead by using `implementation = "lua"` or fallback to the lua implementation,
    -- when the Rust fuzzy matcher is not available, by using `implementation = "prefer_rust"`
    --
    -- See the fuzzy documentation for more information
    fuzzy = { implementation = 'prefer_rust_with_warning' },
  },
  opts_extend = { 'sources.default' },
}
```

This happens on my (Arch) Linux PC, but I feel like I don't experience it (at least, not as often) on my Macbook.

### Reproduction

As others mentioned, difficult to reproduce consistently, but here's what I can say:
- Accepting a completion (in my case, with ctrl+y) seems to trigger the crash, but only occasionally
- Seems to happen most often when I accept a completion that is only a fuzzy match
  - e.g., "mvld" shows "model_validate" as first completion item, I hit ctrl+y to accept it, and neovim crashes

---

Also from journalctl, really similar to @BenjaminPalko 
```
Jul 29 10:03:29 Hypercomputer kernel: traps: libuv-worker[3988552] general protection fault ip:7f3a6b8e0ebc sp:7f3a6dd89550 error:0 in libblink_cmp_fuzzy.so[2dfebc,7f3a6b6f6000+1ef000]
Jul 29 10:03:29 Hypercomputer systemd-coredump[3997391]: Process 3988513 (nvim) of user 1000 terminated abnormally with signal 11/SEGV, processing...
Jul 29 10:03:29 Hypercomputer systemd[1]: Started Process Core Dump (PID 3997391/UID 0).
Jul 29 10:03:29 Hypercomputer systemd-coredump[3997392]: Process 3988513 (nvim) of user 1000 dumped core.

                                                         Module libblink_cmp_fuzzy.so without build-id.
                                                         Stack trace of thread 3988552:
                                                         #0  0x00007f3a6b8e0ebc n/a (libblink_cmp_fuzzy.so + 0x2e0ebc)
                                                         #1  0x00007f3a6b8e0bb1 n/a (libblink_cmp_fuzzy.so + 0x2e0bb1)
                                                         #2  0x00007f3a6b8bb606 n/a (libblink_cmp_fuzzy.so + 0x2bb606)
                                                         #3  0x00007f3a6ef99f7b _Unwind_RaiseException (libgcc_s.so.1 + 0x21f7b)
                                                         #4  0x00007f3a6f0e1773 n/a (libluajit-5.1.so.2 + 0xb773)
                                                         #5  0x00007f3a6f0e753a n/a (libluajit-5.1.so.2 + 0x1153a)
                                                         #6  0x00007f3a6f0ecbfd lua_error (libluajit-5.1.so.2 + 0x16bfd)
                                                         #7  0x00007f3a6b88b15d n/a (libblink_cmp_fuzzy.so + 0x28b15d)
                                                         #8  0x00007f3a6b8832ec n/a (libblink_cmp_fuzzy.so + 0x2832ec)
                                                         #9  0x00007f3a6f0dcf06 n/a (libluajit-5.1.so.2 + 0x6f06)
                                                         #10 0x00007f3a6f0f3ad0 lua_pcall (libluajit-5.1.so.2 + 0x1dad0)
                                                         #11 0x0000559dadccf9be n/a (/usr/bin/nvim + 0x2099be)
                                                         #12 0x00007f3a6f22c644 n/a (libluv.so.1 + 0x1b644)
                                                         #13 0x00007f3a6f0dcf06 n/a (libluajit-5.1.so.2 + 0x6f06)
                                                         #14 0x00007f3a6f0f3ad0 lua_pcall (libluajit-5.1.so.2 + 0x1dad0)
                                                         #15 0x0000559dadccf9be n/a (/usr/bin/nvim + 0x2099be)
                                                         #16 0x00007f3a6f22c8aa n/a (libluv.so.1 + 0x1b8aa)
                                                         #17 0x00007f3a6efba2ba n/a (libuv.so.1 + 0x152ba)
                                                         #18 0x00007f3a6ee1d7eb n/a (libc.so.6 + 0x957eb)
                                                         #19 0x00007f3a6eea120c n/a (libc.so.6 + 0x11920c)

                                                         Stack trace of thread 3988513:
                                                         #0  0x00007f3a6ef06404 n/a (libc.so.6 + 0x17e404)
                                                         #1  0x0000559dadc13610 call_func (/usr/bin/nvim + 0x14d610)
                                                         #2  0x0000559dadcd1bf1 nlua_call (/usr/bin/nvim + 0x20bbf1)
                                                         #3  0x00007f3a6f0dcf06 n/a (libluajit-5.1.so.2 + 0x6f06)
                                                         #4  0x00007f3a6f0f3ad0 lua_pcall (libluajit-5.1.so.2 + 0x1dad0)
                                                         #5  0x0000559dadccebe4 nlua_pcall (/usr/bin/nvim + 0x208be4)
                                                         #6  0x0000559dadccff8b n/a (/usr/bin/nvim + 0x209f8b)
                                                         #7  0x0000559dade02996 state_handle_k_event (/usr/bin/nvim + 0x33c996)
                                                         #8  0x0000559dadbba503 n/a (/usr/bin/nvim + 0xf4503)
                                                         #9  0x0000559dade02864 state_enter (/usr/bin/nvim + 0x33c864)
                                                         #10 0x0000559dadbb76e2 edit (/usr/bin/nvim + 0xf16e2)
                                                         #11 0x0000559dadd444d0 op_change (/usr/bin/nvim + 0x27e4d0)
                                                         #12 0x0000559dadd4b345 do_pending_operator (/usr/bin/nvim + 0x285345)
                                                         #13 0x0000559dadd2b4cc n/a (/usr/bin/nvim + 0x2654cc)
                                                         #14 0x0000559dade028a4 state_enter (/usr/bin/nvim + 0x33c8a4)
                                                         #15 0x0000559dadd28e96 normal_enter (/usr/bin/nvim + 0x262e96)
                                                         #16 0x0000559dadb1c2c0 main (/usr/bin/nvim + 0x562c0)
                                                         #17 0x00007f3a6edaf6b5 n/a (libc.so.6 + 0x276b5)
                                                         #18 0x00007f3a6edaf769 __libc_start_main (libc.so.6 + 0x27769)
                                                         #19 0x0000559dadb1e025 _start (/usr/bin/nvim + 0x58025)

                                                         Stack trace of thread 3988554:
                                                         #0  0x00007f3a6ee25e22 n/a (libc.so.6 + 0x9de22)
                                                         #1  0x00007f3a6ee19fda n/a (libc.so.6 + 0x91fda)
                                                         #2  0x00007f3a6ee1a64c n/a (libc.so.6 + 0x9264c)
                                                         #3  0x00007f3a6ee1cd1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                         #4  0x00007f3a6efc534e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                         #5  0x00007f3a6efba427 n/a (libuv.so.1 + 0x15427)
                                                         #6  0x00007f3a6ee1d7eb n/a (libc.so.6 + 0x957eb)
                                                         #7  0x00007f3a6eea120c n/a (libc.so.6 + 0x11920c)

                                                         Stack trace of thread 3988551:
                                                         #0  0x00007f3a6ee25e22 n/a (libc.so.6 + 0x9de22)
                                                         #1  0x00007f3a6ee19fda n/a (libc.so.6 + 0x91fda)
                                                         #2  0x00007f3a6ee1a64c n/a (libc.so.6 + 0x9264c)
                                                         #3  0x00007f3a6ee1cd1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                         #4  0x00007f3a6efc534e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                         #5  0x00007f3a6efba427 n/a (libuv.so.1 + 0x15427)
                                                         #6  0x00007f3a6ee1d7eb n/a (libc.so.6 + 0x957eb)
                                                         #7  0x00007f3a6eea120c n/a (libc.so.6 + 0x11920c)

                                                         Stack trace of thread 3988553:
                                                         #0  0x00007f3a6ee25e22 n/a (libc.so.6 + 0x9de22)
                                                         #1  0x00007f3a6ee19fda n/a (libc.so.6 + 0x91fda)
                                                         #2  0x00007f3a6ee1a64c n/a (libc.so.6 + 0x9264c)
                                                         #3  0x00007f3a6ee1cd1e pthread_cond_wait (libc.so.6 + 0x94d1e)
                                                         #4  0x00007f3a6efc534e uv_cond_wait (libuv.so.1 + 0x2034e)
                                                         #5  0x00007f3a6efba427 n/a (libuv.so.1 + 0x15427)
                                                         #6  0x00007f3a6ee1d7eb n/a (libc.so.6 + 0x957eb)
                                                         #7  0x00007f3a6eea120c n/a (libc.so.6 + 0x11920c)
                                                         ELF object binary architecture: AMD x86-64
Jul 29 10:03:29 Hypercomputer systemd[1]: systemd-coredump@9-3997391-0.service: Deactivated successfully.
Jul 29 10:03:29 Hypercomputer systemd[1]: systemd-coredump@9-3997391-0.service: Consumed 224ms CPU time, 96.5M memory peak.
```

**Comment by imatpot** [comment]
Has there been any progress on this? I see there's other potentially related issues, like https://github.com/Saghen/blink.cmp/issues/1895 and https://github.com/Saghen/blink.cmp/issues/1905

**Comment by saghen** [comment]
Since it's happening after accepting a completion item, it seems likely that the frecency database, powered by heed/lmdb, would be the culprit. Can you try setting `fuzzy.use_frecency = false` (or `fuzzy.frecency.enabled = false` on main) to see if that resolves the issue?

**Comment by mshytikov** [comment]
In my case I noticed that crash is happening on 'Accepting a completion'.
I can easily reproduce it when I start 2 different instances of neovim. 
~~In a way that second instance would complain about the swap file like showing error `notify.warn W325: Ignoring swapfile from Nvim process ...`
The first instance is always working no crashes. Any other instance which complains about 'swapfile' would crash on accepting a completion~~
**Update**: 
1. Disabling `frecency` did not help (as suggested [here](https://github.com/Saghen/blink.cmp/issues/2031#issuecomment-3246440803))
2. Looks like it actually has to do with process number overlap or something like that. 

My steps to reproduce: 
1. run 2 nvim instances on different files A, B:
1. when I first accept completion on A all good, but accepting suggestion on B will crash it and any next try on B would be crashing. 
1. Closing all A, B but now changing the order
1. I first accept completion on B all good, but accepting suggestion on A will crash

**Comment by mshytikov** [comment]
The recommendation of disabling `fuzzy.use_frecency = false` did not work. 

Based on the source code of the `1.6.0` looks like it is only disabling the scoring (reading). But the crash for me happens on 'accept' (writing).
Looking at the code `fuzzy.db` is always initialized [here](https://github.com/Saghen/blink.cmp/blob/v1.6.0/lua/blink/cmp/fuzzy/init.lua#L20-L30) and [here](https://github.com/Saghen/blink.cmp/blob/v1.6.0/lua/blink/cmp/fuzzy/rust/frecency.rs#L34).

My  current understanding is following:
It uses same `.db` file and creating 'unnamed' database per nvim execution. 
When 'accept completion' happens it writes to the db via [access](https://github.com/Saghen/blink.cmp/blob/v1.6.0/lua/blink/cmp/fuzzy/init.lua#L34) which is delegated to rust.  
I still can't figure out why it is crashing. But I found a way how to avoid it. 
If I create 'db' file per nvim  execution (by changing the db_path in source code)  it works without crashes. Means crash happens somewhere in creating/accessing 'heed' db.   

Note:  To me it looks like `use_frecency` should fully disable db usage including db creation and writes, but I'm very new  to the code base so hard to be certain.

Hope it helps a bit with finding the root cause.

**Comment by saghen** [comment]
You're absolutely right that `use_frecency` should disable writing, I thought that was already the case! Do you mind emailing me your original `.db` files (github@liam.super.fish) so I can try to reproduce it on my system? I've seen reports that the dbs can corrupt at some point and begin causing crashes

**Comment by mshytikov** [comment]
@Saghen thank you for looking into it. 

I was preparing `.db` files for you and just found [this warning on heed](https://docs.rs/heed/latest/src/heed/envs/env_open_options.rs.html#218)  

> Do not use LMDB on remote filesystems, even between processes on the same host 

In my case I actually not only use between processes on the same host, but also I run my nvim in docker container with mounted host folders. 🫣

I assume my `.db` files are not really helpful in this case. And I don't think that they are corrupted. Because if I close all nvim instances and start new ones the first nvim instance would work perfectly without crashes and all other parallel nvim instances  would crash on accepting completion. 

Please let me know if sending `.db` files still make sense.

**Comment by saghen** [comment]
Damn... thanks for digging into that. In that case, I'm going to reimplement the frecency database using fixed size entries (#258) and an append-only file, which should be safe to make lock free since the entries will be smaller than the fs page size. Reading backwards from the end of the file should ensure no surprises during reading as well.

**Comment by mshytikov** [comment]
Thank you !

**Comment by saghen** [comment]
I need to catch a flight but I've thrown together something that seems to work on my system in #2136, if you'd like to give a test. No worries if not though, it requires rust nightly to build, which I imagine would be a PITA in a docker env.

**Comment by mshytikov** [comment]
I just tested it and it all works without crashes. Thank you !

**Comment by imatpot** [comment]
Seems to resolve my issues as well, thank you very much!

**Comment by geril07** [comment]
I might have found a repro with Typescript. I haven't tested with a clean repro/config/cache/etc though.

```typescript
type Str<T extends string = ""> = T;

const a: Str = ""; // <- type inside string value
```

https://github.com/user-attachments/assets/c642e603-cbfa-4d29-acfb-6ef59bb3f7bf

**Comment by anuragkumar2921** [comment]
i just updated my blink.cmp plugin to v1.7.0 via lazy vim and I'm still getting this error.

https://github.com/user-attachments/assets/86de5ff8-576b-43e9-aa9f-e5fd61f4b87b

**Comment by saghen** [comment]
Fixed on latest frizbee, will go out in the next release. Unrelated to this issue though

**Comment by helins** [comment]
@Saghen Is the fix in yet? Because I am updating regularly, currently on the latest commit (`cb87357`) but still having this exact error, at least 20x / day.

I would add though that on my end, it happens without even showing the completion menu. I have disabled `auto_show` since I use completion very sparingly. So I would be typing, without seemingly involving Blink in any way, and this error would pop up randomly.

I see in my notes I first noticed it on June 1st, shortly after updating my plugins. Not 100% sure but likely switching from `30f0a7b5bfed80c1e4b1f7ba065f5c36db0ce025` to `f03e488b37b7581c1ab1c642710ccb2beeb194c1`.
