### ISSUE TITLE
<C-k> keymap overwritten by LazyVim LSP keymap

### ISSUE THREAD

**Issue by stefanboca** [Saghen/blink.cmp#37]
I'm trying out this plugin with LazyVim  and noticed that the `<C-k>` keybinding is instead being bound for LSP signature help by LazyVim.

After adding `vim.notify` statements to the functions that add keybindings for both blink.cmp and LazyVim's LSP, I found that LazyVim's bindings are being set after blink.cmp, overwriting the mapping.

Interesting to note is that this works in `nvim-cmp` because they set key bindings on the first `InsertEnter`.

**Comment by Saghen** [comment]
Should be fixed with https://github.com/Saghen/blink.cmp/commit/506ea74e53a825cc6efd40a46c4129576409e440

**Comment by stefanboca** [comment]
Thank you for the quick response.

I just pulled the latest changes and this issue still persists. It looks like https://github.com/Saghen/blink.cmp/commit/506ea74e53a825cc6efd40a46c4129576409e440 fixes the case where blink overrides pre-existing buffer mappings. However, my issue is that blink is binding `<C-k>`, which is then overwritten by LazyVim.

I believe the reason I didn't previously have this issue with `nvim-cmp` is because `nvim-cmp` sets keymaps on the `InsertEnter` event, rather than on `BufEnter` (which occurs after LazyVim sets the `<C-k>` keybind, overriding blink).
