### ISSUE TITLE
abbreviations does not work

### ISSUE THREAD

**Issue by Snikimonkd** [Saghen/blink.cmp#677]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

i have this remaps and somehow blink.cmp breaks them
```
vim.cmd("cnoreabbrev W! w!")
vim.cmd("cnoreabbrev Q! q!")
vim.cmd("cnoreabbrev Qall! qall!")
vim.cmd("cnoreabbrev Wall! wall!")
vim.cmd("cnoreabbrev Wall wall")
vim.cmd("cnoreabbrev Wq wq")
vim.cmd("cnoreabbrev Wa wa")
vim.cmd("cnoreabbrev wQ wq")
vim.cmd("cnoreabbrev WQ wq")
vim.cmd("cnoreabbrev W w")
vim.cmd("cnoreabbrev Q q")
```

### Relevant configuration

```lua
{
		"saghen/blink.cmp",
		lazy = false, -- lazy loading handled internally

		version = "v0.*",
		opts = {
			keymap = {
				preset = "default",
				["<C-k>"] = { "select_prev", "fallback" },
				["<C-j>"] = { "select_next", "fallback" },
				["<CR>"] = { "accept", "fallback" },
			},

			sources = {
				default = { "lsp", "path", "buffer" },
				cmdline = function()
					local type = vim.fn.getcmdtype()
					-- Search forward and backward
					if type == "/" or type == "?" or type == ":s" then
						return { "buffer" }
					end
					-- Commands
					if type == ":" then
						return {}
					end
					return {}
				end,
			},

			completion = {
				list = {
					selection = "manual",
				},
				accept = {
					auto_brackets = {
						enabled = true,
					},
				},
				menu = {
					enabled = true,
					border = "rounded",
					winhighlight = "Normal:None,FloatBorder:FloatBorder,Search:None",
					scrolloff = 2,
					scrollbar = true,
					draw = {
						padding = { 1, 0 },
						columns = {
							{ "label", gap = 2 },
							{ "kind", "source_name", gap = 1 },
						},
						components = {
							label = {
								text = function(ctx)
									return ctx.label -- .. ctx.label_detail
								end,
							},
							source_name = {
								text = function(ctx)
									return "[" .. ctx.source_name .. "]"
								end,
							},
						},
					},
				},

				-- docs
				documentation = {
					auto_show = true,
					auto_show_delay_ms = 0,
					window = {
						border = "rounded",
						winhighlight = "Normal:None,FloatBorder:FloatBorder,Search:None",
					},
				},
			},
		},
		opts_extend = { "sources.default" },
	},
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

ca05bb33eb071d916d33af08cae8034c3d8002b5

**Comment by Saghen** [comment]
This seems to be a limitation or bug with neovim where using feedkeys ignores abbreviations. This should be solved by #487 but you may want to ask upstream about this

Reproduce with:

```lua
vim.cmd('cnoreabbrev Wa wa')
vim.keymap.set('c', '<CR>', function()
	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>', true, false, true), 'n', false)
end, { expr = true, noremap = true })
```

**Comment by bresilla** [comment]
> This seems to be a limitation or bug with neovim where using feedkeys ignores abbreviations. This may be solved by [#487](https://github.com/Saghen/blink.cmp/pull/487) but you may want to ask upstream about this
> 
> Reproduce with:
> 
> vim.cmd('cnoreabbrev Wa wa')
> vim.keymap.set('c', '<CR>', function()
> 	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>', true, false, true), 'n', false)
> end, { expr = true, noremap = true })

I guess this is still an issue? Cos it completely messes up my `cabbrev`'s.
