### ISSUE TITLE
Can't disable plugin based on filetype

### ISSUE THREAD

**Issue by AbubakrBardien** [Saghen/blink.cmp#824]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I want to disable the plugin whenever I'm using the "dressing.nvim" plugin. For example, when I'm creating a file, or renaming a variable. When I do those things, The filetype I'm in is "DressingInput". 

I also tried the example on your website, that is supposed to disable the plugin for "lua" and "markdown". But that didn't work either

### Relevant configuration

```lua
enabled = function()
    return vim.bo.filetype ~= "DressingInput"
end,
```

### neovim version

NVIM v0.10.3 
Build type: RelWithDebInfo 
LuaJIT 2.1.1731601260 
Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Muizzyranking** [comment]
https://cmp.saghen.dev/recipes.html#disable-per-filetype

**Comment by Saghen** [comment]
Resolved on `main`

**Comment by AbubakrBardien** [comment]
> https://cmp.saghen.dev/recipes.html#disable-per-filetype

@Muizzyranking I tried that, it doesn't work

**Comment by AbubakrBardien** [comment]
I understand the logic. I also tried to disable it on "lua" files for testing purposes. But it's still not working.

My code:
```lua
enabled = function()
    local disabled_filetypes = { "lua", "DressingInput" }
    return not vim.tbl_contains(disabled_filetypes, vim.bo.filetype)
end,
```

I'm already at the latest version of the plugin (I think):
![2024-12-31-004706_hyprshot](https://github.com/user-attachments/assets/953ae7f8-9ecf-4a09-bba0-12637a95de1a)
